# This rule is not used by the project auto-mtls itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the automtls.kupher.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: auto-mtls
    app.kubernetes.io/managed-by: kustomize
  name: automtls--resource-editor-role
rules:
- apiGroups:
  - automtls.kupher.io
  resources:
  - automtls--resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automtls.kupher.io
  resources:
  - automtls--resources/status
  verbs:
  - get
