---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server
  annotations:
    auto-mtls.kupher.io/enabled: "true"
spec:
  selector:
    app: mtls-server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  labels:
    app: mtls-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      containers:
        - name: mtls-server
          image: kupher/mtls-server-example:v0.0.3
          ports:
            - containerPort: 8443



